application: epicollectserver-hrd
version: 161
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /css
  static_dir: css
  
- url: /instructions/
  static_files: instructions/default.html
  upload: instructions/default.html
  
- url: /instructions
  static_dir: instructions

- url: /(default.html?)?
  static_files: default.html
  upload: default.html

- url: /create1.html
  static_files: create1.html
  upload: create1.html

- url: /create-project.html
  static_files: create-project.html
  upload: create-project.html
  
- url: /createOrEditForm.html
  static_files: createOrEditForm.html
  login: required
  upload: createOrEditForm.html
  
- url: /checkboxgrouptest.html
  static_files: checkboxgrouptest.html
  upload: checkboxgrouptest.html

- url: /zipme
  script: zipme.py

- url: /test.*
  script: gaeunit.py

- url: /feedback
  script: main.py
  login: required

- url: .*
  script: main.py